version: '3'
services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - "8880:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php
  php:
    container_name: yii_php
    build: ./docker/images/php
    volumes:
      - ./:/var/www